// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvo2O2p1VxfEQH9iOT_stSW1lYldr2deM',
    appId: '1:506674408990:web:cfd2f01251402723c1080f',
    messagingSenderId: '506674408990',
    projectId: 'bakery-68b0b',
    authDomain: 'bakery-68b0b.firebaseapp.com',
    storageBucket: 'bakery-68b0b.appspot.com',
    measurementId: 'G-GLRHRVR4YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfNopMuoxo0-yVWTq87ILLUI2Bw41X12M',
    appId: '1:506674408990:android:6c4142b52906b689c1080f',
    messagingSenderId: '506674408990',
    projectId: 'bakery-68b0b',
    storageBucket: 'bakery-68b0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALQsinCo6UHby-4kxwVtGtf4sV8e18rk4',
    appId: '1:506674408990:ios:9e08ad6c0ec2a971c1080f',
    messagingSenderId: '506674408990',
    projectId: 'bakery-68b0b',
    storageBucket: 'bakery-68b0b.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALQsinCo6UHby-4kxwVtGtf4sV8e18rk4',
    appId: '1:506674408990:ios:9e08ad6c0ec2a971c1080f',
    messagingSenderId: '506674408990',
    projectId: 'bakery-68b0b',
    storageBucket: 'bakery-68b0b.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvo2O2p1VxfEQH9iOT_stSW1lYldr2deM',
    appId: '1:506674408990:web:203d396dd828a5b4c1080f',
    messagingSenderId: '506674408990',
    projectId: 'bakery-68b0b',
    authDomain: 'bakery-68b0b.firebaseapp.com',
    storageBucket: 'bakery-68b0b.appspot.com',
    measurementId: 'G-6WDDZKZS33',
  );
}
